apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  postgres-user: {{ .Values.global.postgres.user | quote }}
  postgres-password: {{ .Values.global.postgres.password | quote }}
  postgres-db: {{ .Values.global.postgres.database | quote }}
