telemetry-simulator:
  image:
    repository: ghcr.io/apeonfire/vantage-telemetry-simulator

ingestion-service:
  image:
    repository: ghcr.io/apeonfire/vantage-ingestion-service

alert-engine:
  image:
    repository: ghcr.io/apeonfire/vantage-alert-engine

event-store-service:
  image:
    repository: ghcr.io/apeonfire/vantage-event-store-service

api-service:
  image:
    repository: ghcr.io/apeonfire/vantage-api-service

dashboard:
  image:
    repository: ghcr.io/apeonfire/vantage-dashboard
